[package]
name = "apis-saltans-hw"
description = "Zigbee hardware library."
authors = ["Richard Neumann <neumann@paulmann.de>"]
license = "MIT"
repository = "https://github.com/PaulmannLighting/apis-saltans"
keywords = ["zigbee", "hardware", "library"]
categories = ["network-programming"]
documentation = "https://docs.rs/apis-saltans-hw"
version = "0.13.0"
edition = "2024"
exclude = [".gitignore", "ARCHITECTURE.md", "TODO.md"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
bytes = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
tokio = { workspace = true, features = ["sync"], optional = true }
zb-aps = { workspace = true, optional = true }
zb-core = { workspace = true, optional = true }
zb-nwk = { workspace = true, optional = true }
zb-zdp = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt"] }

[features]
default = []
types = [
    "dep:bytes",
    "dep:thiserror",
    "dep:tokio",
    "dep:zb-aps",
    "dep:zb-core",
    "dep:zb-zdp",
]
coordinator = ["types"]
driver = ["types", "dep:zb-nwk"]
serde = ["types", "dep:serde", "serde/derive", "zb-core/serde"]

[lints]
workspace = true
